image: python:3.6

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/.cache"
  key: "$CI_PROJECT_ID"
  
stages:
  - build
  - test
  - deploy
  
build:
  stage: build
  script:
    - pip install -r requirements.txt
    - mkdocs --verbose build
  artifacts:
    paths:
    - public
    expire_in: 1 week
    
check_links:
  stage: test
  script:
    - pip install -r util/requirements.txt
    - python util/scrape_urls.py public
  allow_failure: true
  artifacts:
    paths:
    - public
    expire_in: 1 week
  
pages:
  stage: deploy
  script:
  - ls -l public
  - gzip -k -6 -r public/assets/stylesheets
  - gzip -k -6 -r public/assets/javascripts
  - find public -type f -name "*.html"
  - find public -type f -name "*.html" -exec htmlmin {} {} \;
  - find public -type f -name "*.html" -exec gzip --keep --verbose {} \;
  artifacts:
    paths:
    - public
  only:
    - master@NERSC/nersc.gitlab.io
