image: python:3.6

stages:
  - test
  - deploy
  
test:
  stage: test
  script:
    - pip install -r requirements.txt
    - mkdocs --verbose build
    - ls -l public
    - pip install -r util/requirements.txt
    - python util/scrape_urls.py public
  except:
    - master@NERSC/nersc.gitlab.io
  
pages:
  stage: deploy
  script:
  - pip install -r requirements.txt
  - mkdocs --verbose build
  - ls -l public
  - gzip -k -6 -r public/assets/stylesheets
  - gzip -k -6 -r public/assets/javascripts
  - find public -type f -name "*.html"
  - find public -type f -name "*.html" -exec htmlmin {} {} \;
  - find public -type f -name "*.html" -exec gzip --keep --verbose {} \;
  artifacts:
    paths:
    - public
  only:
    - master@NERSC/nersc.gitlab.io
