image: python:2.7

pages:
  stage: deploy
  script:
  - pip install -r requirements.txt
  - mkdocs --verbose build
  - ls -l public
  - pwd  
  - "gzip -k -6 -r public/assets/stylesheets"
  - gzip -k -6 -r public/assets/javascript

  artifacts:
    paths:
    - public
  only:
  - master
