image: python:3.6

stages:
  - build
  - test
  - deploy
  - post-deploy

build:
  stage: build
  script:
    - mkdir -p .build_cache
    - pip install --cache-dir=.build_cache -r requirements.txt
    - mkdocs --verbose build
  artifacts:
    paths:
    - public
    expire_in: 1 week
  cache:
    paths:
      - .build_cache
    key: "build-$CI_COMMIT_REF_SLUG"
    
check_links:
  stage: test
  script:
    - mkdir -p .links_cache
    - pip install --cache-dir=.links_cache -r util/requirements.txt
    - python util/scrape_urls.py public
  allow_failure: true
  cache:
    paths:
      - .links_cache
    key: "links-$CI_COMMIT_REF_SLUG"
  
markdown_lint:
  image: node
  stage: test
  script:
    - npm install -g markdownlint-cli
    - markdownlint docs
  allow_failure: true
            
pages:
  stage: deploy
  script:
  - ls -l public
  - gzip -k -6 -r public/assets/stylesheets
  - gzip -k -6 -r public/assets/javascripts
  - find public -type f -name "*.html"
  - find public -type f -name "*.html" -exec htmlmin {} {} \;
  - find public -type f -name "*.html" -exec gzip --keep --verbose {} \;
  artifacts:
    paths:
    - public
  only:
    - master@NERSC/nersc.gitlab.io

update-search-api:
  stage: post-deploy
  image: ubuntu:18.04
  before_script:
    - apt-get update; apt-get -y install curl
  script:
    - "curl --request POST \
    --url https://nersc-docs-search-app-214117.appspot.com/reindex \
    --header 'content-type: application/json' \
    --data '{\"source\":\"docs\"}'"
  only:
    - master@NERSC/nersc.gitlab.io
