pages:
  - Home: index.md
  - Accounts:
      - Accounts : accounts/index.md
      - Passwords : accounts/passwords.md
      - Policy : accounts/policy.md
  - Connecting:
      - SSH : connect/ssh.md
      - NX : connect/nx.md
      - Jupyter : services/jupyter.md
  - Running Jobs:
    - Overview: jobs/index.md
    - Examples: jobs/examples.md
    - Best Practices: jobs/best-practices.md
    - Workflow Tools : jobs/workflow-tools.md
    - Reservations: jobs/reservations.md
    - Policy: jobs/policy.md
  - Applications:
    - Quantum ESPRESSO : applications/quantum-espresso/index.md
    - NAMD : applications/namd/index.md
    - VASP : applications/vasp/index.md
  - Analytics:
      - Jupyter : services/jupyter.md
  - Data:
      - Management : data/management.md
      - Transfer : data/transfer.md
      - Visualization : data/visualization.md
      - Formats : data/formats.md
      - Policy: data/policy.md
  - Performance:
    - Optimization strategy : performance/optimization-strategy.md
    - Vectorization : performance/vectorization.md
    - Parallelism : performance/parallelism.md
    - Profiling : performance/profiling.md
    - I/O : performance/io.md
    - Portability: performance/portability.md
    - Case Studies:
        - EMGeo : performance/case-studies/emgeo/index.md
        - MFDn : performance/case-studies/mfdn/index.md
        - Quantum ESPRESSO Exact Exchange : performance/case-studies/quantum-espresso/index.md
        - WARP: performance/case-studies/warp/index.md
        - XGC1: performance/case-studies/xgc1/index.md
  - Services:
      - Spin :
        - services/spin/index.md
        - services/spin/getting_started_guide.md
      - Science Gateways : services/science-gateways.md
      - NEWT : services/newt.md
      - Jupyter : services/jupyter.md
  - Development:
    - Containers (Shifter):
        - Overview : development/shifter/overview.md
        - How to use : development/shifter/how-to-use.md
    - Developer Tools:
        - DDT : development/performance-debugging-tools/ddt.md
#        - TotalView : development/performance-debugging-tools/totalview.md
#        - GDB : development/performance-debugging-tools/gdb.md
    - Compilers : development/compilers.md
    - High-level Programming Environments:
        - Python : development/high-level-environments/python.md
#        - Julia : development/high-level-environments/julia.md
#        - Matlab : development/high-level-environments/matlab.md
    - Programming Models:
        - MPI : development/programming-models/mpi.md
        - OpenMP : development/programming-models/openmp.md
        - UPC++ : development/programming-models/upcxx.md
        - Chapel : development/programming-models/chapel.md
        - Kokkos : development/programming-models/kokkos.md
        - Raja : development/programming-models/raja.md
        - Coarrays : development/programming-models/coarrays.md
    - Libraries:
        - MKL : development/libraries/mkl/index.md
        - FFTW : development/libraries/fftw/index.md
        - LibSci : development/libraries/libsci/index.md
        - HDF5 : development/libraries/hdf5/index.md
        - NetCDF : development/libraries/netcdf/index.md
                              
  - Environment: environment/environment.md
  - Systems:
      - Cori : systems/cori/index.md
      - Edison : systems/edison/index.md
      - PDSF : systems/pdsf/index.md
      - Genepool : systems/genepool.md
      - Filesystems:
          - Overview: systems/filesystems/index.md
          - Global Home: systems/filesystems/global-home.md
          - Global Common: systems/filesystems/global-common.md
          - Project: systems/filesystems/project.md
  - PDSF:
    - slurm :
      - overview : pdsf/slurm/README.md
      - LZ pulseFinder CVMFS : pdsf/slurm/lz-pulseFinder/Readme.md
      - Atlas madGraph multi-core : pdsf/slurm/atlas-madGraph/Readme.md
      - DayaBay NuWa : pdsf/slurm/dyb-nuwa/Readme.md
      - Majorana skim : pdsf/slurm/majorana-skim/Readme.md
      - STAR root4star :  pdsf/slurm/star-bfc/Readme.md
      - STAR interactive :  pdsf/slurm/star-bfc/ws2-interactive-starExp.md
  - Help: help/index.md
#      - 
#  - JGI:
#      - Pipelines : jgi/pipelines.md
#  - Tutorials:
#    - Demo : demo/demo.md
#    - Tables : demo/table.md
#    - Dropdown: demo/dropdown.md

# Project Information
site_name: NERSC Documentation
site_description: NERSC Documentation
site_author: NERSC
site_dir: public
site_url: "https://docs.nersc.gov"
#repo_name: NERSC/documentation
#repo_url: https://gitlab.com/NERSC/documentation

# Configuration
strict: true

theme:
  name: material
  custom_dir: material
  favicon: img/favicon.ico
  palette:
    primary: mute-turquoise
    accent: orange
  logo: img/logo.png

# Extensions
markdown_extensions:
  - footnotes
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols(fractions=false)
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - pymdownx.snippets

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
extra_css:
  - stylesheets/extra.css

google_analytics:
  - 'UA-115581982-1'
  - 'auto'
