nav:
  - 主页: index.md
  - 账号:
    - 账号申请: accounts/apply.md
  #   - 密码: accounts/password.md
  #   - 账号管理: accounts/management.md
  #   - 机时充值: accounts/charge.md
  #   - 收费细则: accounts/fee.md
  - 登陆:
    # - 登陆节点: 登陆/登陆节点.md
    - SSH: login/SSH.md
    - Open OnDemand: login/OpenOnDemand.md
  # - 文件系统:
  #   - 概览: 文件系统/概览.md
  #   - 数据传输: 文件系统/数据传输.md
  #   - 与校云计算文件交互: 文件系统/云平台.md
  #   - 与其他用户共享文件: 文件系统/共享文件.md 
  - 作业:
    - Slurm概览: job/slurm.md
    # - 脚本式作业: 作业/脚本式作业.md
    # - MPI、OpenMP、CUDA作业示例: 作业/MPI、OpenMP、CUDA作业示例.md
    # - 作业脚本样例: 作业/作业脚本样例.md
    # - 交互式作业: 作业/交互式作业.md
    # - 队列选择: 作业/队列选择.md
    - 节点预约: job/reservation.md
    # - 作业优先级: 作业/作业优先级.md
    # - 容器: 作业/容器/singularity.md
  - 预置软件环境: module/module.md
    # - Module Environment: module/module.md
  - 应用软件:
  #   - Python: 应用软件/Python.md
  #   - Nektar++: 应用软件/Nektar.md
  #   - Lammps: 应用软件/Lammps.md
    - VASP: application/VASP.md
    - Amber: application/Amber.md
  #   - VMD: 应用软件/VMD.md
  #   - nwchen: 应用软件/nwchen.md
  #   - Desmond and Maestro: 应用软件/Desmond_and_Maestro.md
  #   - Gromacs: 应用软件/Gromacs.md
  #   - FFTW: 应用软件/FFTW.md
  #   - OpenFoam: 应用软件/OpenFoam.md
  #   - GNU Library: 应用软件/GNU.md
  #   - MPI4PY: 应用软件/MPI4PY.md
  #   - Pytorch: 应用软件/Pytorch.md
  #   - TensorFlow: 应用软件/TensorFlow.md
  #   - MXNet: 应用软件/MXNet.md
  #   - HIC-Pro: 应用软件/HIC-Pro.md
  #   - Octave: 应用软件/Octave.md
  #   - Perl: 应用软件/Perl.md
  #   - Spark: 应用软件/Spark.md
  #   - R: 应用软件/R.md
  #   - 商业软件: 应用软件/商业软件.md
  - 常见问题: FAQ/faq.md
    # - faq: FAQ/faq.md

# Project Information
site_name: Pi Documentation
site_description: Pi Documentation
site_author: SJTU HPC Team
site_dir: public
site_url: "http://docs.hpc.sjtu.edu.cn"
repo_name: Github/sjtuhpcc/docs
repo_url: https://github.com/sjtuhpcc/docs.sjtu.edu.cn
edit_uri: tree/master/docs/

# Configuration
strict: false

theme:
  name: material
  custom_dir: material
  favicon: img/favicon.png
  palette:
    primary: mute-turquoise
    accent: orange
  logo: img/logos.png

# Extensions
markdown_extensions:
  - meta
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
extra_css:
  - stylesheets/extra.css

google_analytics:
  - 'UA-115581982-1'
  - 'auto'

plugins:
  - search
  - minify:
      minify_html: true

