pages:
  - Home: index.md
  - Accounts:
      - Accounts : accounts/accounts.md
      - Passwords : accounts/passwords.md
      - Policy : accounts/policy.md
  - Data:
      - Analytics : data/analytics.md
      - Management : data/management.md
      - Transfer : data/transfer.md
      - Visualization : data/visualization.md
      - Storage:
          - Best Practices : data/storage/best-practices.md
          - Filesystems : data/storage/filesystems.md
          - Formats : data/storage/formats.md
  - Performance:
    - Optimization strategy : performance/optimization-strategy.md
    - Vectorization : performance/vectorization.md
    - Parallelism : performance/parallelism.md
    - Profiling : performance/profiling.md
    - IO : performance/io.md
    - Portability: performance/portability.md
    - Case Studies:
        - EMGeo : performance/case-studies/emgeo/emgeo.md
        - MFDn : performance/case-studies/mfdn/mfdn.md
        - Quantum ESPRESSO Exact Exchange : performance/case-studies/quantum-espresso/quantum-espresso.md
        - WARP: performance/case-studies/warp/warp.md
        - XGC1: performance/case-studies/xgc1/xgc1.md
  - Services:
      - Science Gateways : services/science-gateways.md
      - NEWT : services/newt.md
      - Jupyter : services/jupyter.md
      - NX : services/nx.md
  - Running Jobs:
    - Overview: jobs/overview.md
    - Batch jobs: jobs/batch.md
    - Interactive work: jobs/interactive.md
    - Best Practices: jobs/best-practices.md
    - Serial Jobs: jobs/serial.md
  - Software:
    - Environment: software/environment.md
    - Shifter:
        - Overview : software/shifter/overview.md
        - How to use : software/shifter/how-to-use.md
        - Examples : software/shifter/examples.md
    - Applications:
        - Quantum ESPRESSO : software/applications/quantum-espresso.md
        - NAMD : software/applications/namd.md
        - VASP : software/applications/vasp.md
    - Developer Tools:
        - DDT : software/performance-debugging-tools/ddt.md
        - TotalView : software/performance-debugging-tools/totalview.md
        - GDB : software/performance-debugging-tools/gdb.md
    - Workflow Tools : software/workflow-tools.md
    - Analytics : software/analytics.md
    - Compilers : software/compilers.md
    - High-level Programming Environments:
        - Python : software/high-level-environments/python.md
        - Julia : software/high-level-environments/julia.md
        - Matlab : software/high-level-environments/matlab.md
    - Programming Models:
        - MPI : software/programming-models/mpi.md
        - OpenMP : software/programming-models/openmp.md
        - UPC++ : software/programming-models/upcxx.md
        - Chapel : software/programming-models/chapel.md
        - Kokkos : software/programming-models/kokkos.md
        - Raja : software/programming-models/raja.md
        - Coarrays : software/programming-models/coarrays.md
    - Libraries:
        - MKL : software/libraries/mkl.md
        - FFTW : software/libraries/fftw.md
        - LibSci : software/libraries/libsci.md
  - Systems:
      - Cori : systems/cori.md
      - Edison : systems/edison.md
      - PDSF : systems/pdsf.md
      - Genepool : systems/genepool.md
  - PDSF community:
    - slurm :
      - overview : 'pdsf/slurm/README.md'
      - 'LZ pulseFinder CVMFS' : pdsf/slurm/lz-pulseFinder/Readme.md
      - 'Atlas madGraph multi-core' : pdsf/slurm/atlas-madGraph/Readme.md
  - JGI community:
      - Pipelines : jgi/pipelines.md
  - Tutorials:
    - Demo : demo/demo.md
    - Tables : demo/table.md
    - Dropdown: demo/dropdown.md

# Project Information
site_name: NERSC Documentation
site_description: NERSC Documentation
site_author: NERSC
site_dir: public
repo_name: NERSC/documentation
repo_url: https://gitlab.com/NERSC/documentation

# Configuration
strict: true

theme:
  name: material
  custom_dir: material
  favicon: img/favicon.ico
  palette:
    primary: mute-turquoise
    accent: orange
  logo: img/logo.png

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols(fractions=false)
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - pymdownx.snippets

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
extra_css:
  - stylesheets/extra.css
