pages:
  - Home: index.md
  - Accounts:
      - Accounts : accounts/accounts.md
      - Passwords : accounts/passwords.md
      - Policy : accounts/policy.md
  - Data:
      - Analytics : data/analytics.md
      - Management : data/management.md
      - Transfer : data/transfer.md
      - Visualization : data/visualization.md
      - Formats : data/formats.md
      - Filesystems:
          - Overview: data/filesystems/index.md
          - 'Global Home': data/filesystems/global-home.md
          - 'Global Common': data/filesystems/global-common.md
          - Project: data/filesystems/project.md
          - 'Edison Scratch': data/filesystems/edison-scratch.md
          - 'Cori Scratch': data/filesystems/cori-scratch.md
          - 'Cori Burst Buffer': data/filesystems/cori-burst-buffer.md
  - Performance:
    - Optimization strategy : performance/optimization-strategy.md
    - Vectorization : performance/vectorization.md
    - Parallelism : performance/parallelism.md
    - Profiling : performance/profiling.md
    - IO : performance/io.md
    - Portability: performance/portability.md
    - Case Studies:
        - EMGeo : performance/case-studies/emgeo/emgeo.md
        - MFDn : performance/case-studies/mfdn/mfdn.md
        - Quantum ESPRESSO Exact Exchange : performance/case-studies/quantum-espresso/quantum-espresso.md
        - WARP: performance/case-studies/warp/warp.md
        - XGC1: performance/case-studies/xgc1/xgc1.md
  - Services:
      - Spin : services/spin/index.md
      - Science Gateways : services/science-gateways.md
      - NEWT : services/newt.md
      - Jupyter : services/jupyter.md
      - NX : services/nx.md
  - Running Jobs:
    - Overview: jobs/index.md
    - Batch jobs: jobs/batch.md
    - Interactive jobs: jobs/interactive.md
    - Best Practices: jobs/best-practices.md
    - Serial Jobs: jobs/serial.md
    - Shifter:
      - Overview : jobs/shifter/overview.md
      - How to use : jobs/shifter/how-to-use.md
      - Examples : jobs/shifter/examples.md
    - Workflow Tools : jobs/workflow-tools.md

  - Applications:
    - Quantum ESPRESSO : applications/quantum-espresso.md
    - NAMD : applications/namd/index.md
    - VASP : applications/vasp/index.md
  - Analytics : analytics/analytics.md
  - Development:
#    - Developer Tools:
#        - DDT : development/performance-debugging-tools/ddt.md
#        - TotalView : development/performance-debugging-tools/totalview.md
#        - GDB : development/performance-debugging-tools/gdb.md
    - Compilers : development/compilers.md
    - High-level Programming Environments:
        - Python : development/high-level-environments/python.md
#        - Julia : development/high-level-environments/julia.md
#        - Matlab : development/high-level-environments/matlab.md
    - Programming Models:
        - MPI : development/programming-models/mpi.md
        - OpenMP : development/programming-models/openmp.md
        - UPC++ : development/programming-models/upcxx.md
        - Chapel : development/programming-models/chapel.md
        - Kokkos : development/programming-models/kokkos.md
        - Raja : development/programming-models/raja.md
        - Coarrays : development/programming-models/coarrays.md
    - Libraries:
        - MKL : development/libraries/mkl.md
        - FFTW : development/libraries/fftw.md
        - LibSci : development/libraries/libsci.md
  - Environment: environment/environment.md
  - Systems:
      - Cori : systems/cori.md
      - Edison : systems/edison.md
      - PDSF : systems/pdsf.md
#      - Genepool : systems/genepool.md
  - PDSF:
    - slurm :
      - overview : 'pdsf/slurm/README.md'
      - 'LZ pulseFinder CVMFS' : pdsf/slurm/lz-pulseFinder/Readme.md
      - 'Atlas madGraph multi-core' : pdsf/slurm/atlas-madGraph/Readme.md
      - 'DayaBay NuWa' : pdsf/slurm/dyb-nuwa/Readme.md
      - 'Majorana skim' : pdsf/slurm/majorana-skim/Readme.md
      - 'STAR root4star' :  pdsf/slurm/star-bfc/Readme.md
      - 'STAR interactive' :  pdsf/slurm/star-bfc/ws2-interactive-starExp.md
#  - JGI:
#      - Pipelines : jgi/pipelines.md
#  - Tutorials:
#    - Demo : demo/demo.md
#    - Tables : demo/table.md
#    - Dropdown: demo/dropdown.md

# Project Information
site_name: NERSC Documentation
site_description: NERSC Documentation
site_author: NERSC
site_dir: public
site_url: "https://docs.nersc.gov"
#repo_name: NERSC/documentation
#repo_url: https://gitlab.com/NERSC/documentation

# Configuration
strict: true

theme:
  name: material
  custom_dir: material
  favicon: img/favicon.ico
  palette:
    primary: mute-turquoise
    accent: orange
  logo: img/logo.png

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols(fractions=false)
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - pymdownx.snippets

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
extra_css:
  - stylesheets/extra.css

google_analytics:
  - 'UA-115581982-1'
  - 'auto'
